/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
} from "./agent-session-runtime.ts";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
	createSemanticIndexOptionsFromEnv,
} from "./agent-session-services.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export type { CompactionResult } from "./compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
export { areExperimentalFeaturesEnabled } from "./experimental.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentSettledEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type InlineExtension,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export {
	createNativeBenchmarkCliPlan,
	declareNativeBenchmarkCapabilities,
	getNativeDubaiBoomBenchmarkTasks,
	type NativeBenchmarkCapabilityDeclaration,
	type NativeBenchmarkCapabilityOptions,
	type NativeBenchmarkCliOptions,
	type NativeBenchmarkCliPlan,
	type NativeBenchmarkCorpusArtifacts,
	type NativeBenchmarkCorpusOptions,
	type NativeBenchmarkCorpusResult,
	type NativeBenchmarkEventTrace,
	type NativeBenchmarkJsonlTraceEntry,
	type NativeBenchmarkSemanticEmbeddingOptions,
	type NativeBenchmarkShellCommandValidationOptions,
	type NativeBenchmarkShellCommandValidationResult,
	type NativeBenchmarkTask,
	type NativeBenchmarkTaskCorpus,
	type NativeBenchmarkTaskOptions,
	type NativeBenchmarkTaskResult,
	type NativeBenchmarkValidationOptions,
	type NativeBenchmarkValidationResult,
	type NativeBenchmarkWebAccessStatus,
	type NativeBenchmarkWorkspace,
	type NativeBenchmarkWorkspaceOptions,
	nativeBenchmarkCorpusSummaryMarkdown,
	nativeBenchmarkJsonlTraceEntries,
	nativeBenchmarkMarkdownReport,
	runNativeBenchmarkCli,
	runNativeBenchmarkCorpus,
	runNativeBenchmarkTask,
	validateNativeBenchmarkShellCommand,
	writeNativeBenchmarkCorpusArtifacts,
	writeNativeBenchmarkJsonlTrace,
	writeNativeBenchmarkMarkdownReport,
} from "./native-benchmark.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
export {
	createOpenAICompatibleWorkspaceEmbeddingProvider,
	type OpenAICompatibleWorkspaceEmbeddingProviderOptions,
} from "./workspace-embedding-provider.ts";
export {
	type WorkspaceEmbeddingRuntimeEndpoint,
	WorkspaceEmbeddingRuntimeError,
	WorkspaceEmbeddingRuntimeManager,
	type WorkspaceEmbeddingRuntimeManagerOptions,
	type WorkspaceEmbeddingRuntimeOperations,
	type WorkspaceEmbeddingRuntimeProcess,
	type WorkspaceEmbeddingRuntimeStartOptions,
	type WorkspaceEmbeddingRuntimeState,
	type WorkspaceEmbeddingRuntimeStateValue,
} from "./workspace-embedding-runtime-manager.ts";
export {
	type WorkspaceSemanticEmbeddingProvider,
	WorkspaceSemanticIndex,
	type WorkspaceSemanticIndexOptions,
	type WorkspaceSemanticIndexResult,
	type WorkspaceSemanticIndexStatus,
	type WorkspaceSemanticRelatedContext,
	type WorkspaceSemanticRerankCandidate,
	type WorkspaceSemanticRerankProvider,
	type WorkspaceSemanticSearchResponse,
	type WorkspaceSemanticVectorStatus,
} from "./workspace-semantic-index.ts";
